import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AppContext, AppWrapper } from "./context";
import { useContext } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <AppWrapper>
          {children}
        </AppWrapper>
      </body>
    </html>
  );
}
